FROM docker.io/postgres:18.1-alpine3.23

COPY ./backend/dependencies/pg_fzy /pg_fzy

RUN apk add --no-cache make postgresql-dev libpq

RUN cd /pg_fzy && make && make install

# Usage
# - Mount volume on PGDATA to persist database: PGDATA=/var/lib/postgresql/18/docker
# - Mount docker-entrypoint-initdb.d/ on /docker-entrypoint-initdb.d/ for additional initialization.
#   These initialization files will be executed in sorted name order as defined by the current locale, which defaults to en_US.utf8.
#   In the case of FreezeMan, you put your .pgsql.gz database dumps there but prepend the filename with a number lower than 2
#   (e.g. `1-2025-12-17.pgsql.gz`).
